language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
script:
  - npm test
  - 'mkdir -p tmp && ./bin/product-type-generator --types data/sample-product-types.csv --attributes data/sample-product-types-attributes.csv --target ./tmp --zip'
  - 'mkdir -p tmp && ./bin/product-type-generator --types data/marketplace-types.csv --attributes data/marketplace-attributes.csv --target ./tmp --withRetailer --zip'
notifications:
  hipchat:
    rooms:
      - secure: BbMUlILTPGhOX0ZBNqyCq0LpqwRNTOmuqv8gsg83LiDPy4SI/YsjAOQLlrbnoXLECAQMfRBwnED1XVJnskgJbj/VFL+q0hAa0GWfp8gLj7PAv40TYM7+pj6KDxJMWh3ZMWrQ2ixNRAjbuGnP2AfL0Gn6hj6NaxFwyIGQrb7sHKo=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
